spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mobilele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mobilele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
#    username: ${db_username}
#    password: ${db_password}
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    defer-datasource-initialization: true
#    properties:
#      hibernate:
#        format_sql: true
#    hibernate:
#      ddl-auto: update
  sql:
    init:
      mode: never

default.admin.pass: ${DEFAULT_ADMIN_PASS_TEST}

open.exchange.rates:
  schema: https
  host: openexchangerates.org
  path: /api/latest.json
  app_id: ${APP_ID:test}
  symbols: EUR,BGN
  enabled: false